version: '2.1'

services:
  unifi:
    image: "${CI_REGISTRY_IMAGE:jcberthon/unifi}:${IMAGE_TAG:-latest}"
    restart: always
    hostname: 'unifi'
    container_name: unifi
    mem_limit: 1024m
    memswap_limit: 2048m
    init: true
    cap_drop:
      - ALL
#    network_mode: "host"
#    userns_mode: "host"
    ports:
      - '6789:6789'
      - '8080:8080'
      - '8443:8443'
      - '8843:8843'
      - '10001:10001/udp'
    volumes:
      - '/docker/unifi/data:/usr/lib/unifi/data'
      - '/docker/unifi/log:/usr/lib/unifi/logs'

